### ISSUE TITLE
 snoopy-ng Kali 2.X - No module named libmproxy 

### ISSUE THREAD

**Issue by dawz0r** [sensepost/snoopy-ng#80]
Hello. When I try to start snoopy-ng I get the following message. I have tried to install the module by reinstalling mitmproxy. But I only fall further down the rabbithole.
Does anybody have some good input on how I should solve this?

Running on a Raspberry Pi 3 with the latest update of Kali img.

root@kali:~# snoopy

---

/ **)( ( )( _ )( _ )( _ ( \/ )
\** \ ) ( )(_)( )(_)( )**_/ \ /
(**_/(_)\_)(_____)(_____)(**) (**)
Version: 2.0
Code: glenn@sensepost.com // @glennzw
Visit: www.sensepost.com // @sensepost
License: Non-commercial use

Traceback (most recent call last):
File "/usr/bin/snoopy", line 428, in <module>
main()
File "/usr/bin/snoopy", line 353, in main
plugins = common.get_plugins()
File "/root/snoopy-ng/includes/common.py", line 24, in get_plugins
m = **import**(plug, fromlist="Snoop").Snoop
File "/root/snoopy-ng/plugins/mitmproxy.py", line 17, in <module>
from includes.mitm import *
File "/root/snoopy-ng/includes/mitm.py", line 4, in <module>
from libmproxy import proxy, flow, platform
ImportError: No module named libmproxy

**Comment by meulemans** [comment]
Rename the libmproxy to mitmproxy and the issue should be fixed.

**Comment by dawz0r** [comment]
Appreciate the tip. Have trouble getting it to work . Are you able to be more specific .

**Comment by ErinBejtaa** [comment]
cd snoopy-ng/includes/
gedit mitm.py 
at line 4 libmproxy change it to mitmproxy

**Comment by TheRealXaiL** [comment]
Did this work? Has someone submitted a pull request for this?

**Comment by lugfug** [comment]
I'm having the same issue and the name change does not fix the issue. 

I issue the command, snoopy

The software reports the following output. 

`Traceback (most recent call last):
  File "/usr/bin/snoopy", line 428, in <module>
    main()
  File "/usr/bin/snoopy", line 353, in main
    plugins = common.get_plugins()
  File "/root/mytemp/snoopy-ng/includes/common.py", line 24, in get_plugins
    m = __import__(plug, fromlist="Snoop").Snoop
  File "/root/mytemp/snoopy-ng/plugins/mitmproxy.py", line 17, in <module>
    from includes.mitm import *
  File "/root/mytemp/snoopy-ng/includes/mitm.py", line 5, in <module>
    from libmproxy import proxy, flow, platform
ImportError: No module named libmproxy`

I change the 4th line (libmproxy change it to mitmproxy )in the file  mitm.py  

`from mitmproxy import proxy, flow, platform
#from libmproxy import proxy, flow, platform
`

I run the command again, snoopy

The software reports a similar error. 

`Traceback (most recent call last):
  File "/usr/bin/snoopy", line 428, in <module>
    main()
  File "/usr/bin/snoopy", line 353, in main
    plugins = common.get_plugins()
  File "/root/mytemp/snoopy-ng/includes/common.py", line 24, in get_plugins
    m = __import__(plug, fromlist="Snoop").Snoop
  File "/root/mytemp/snoopy-ng/plugins/mitmproxy.py", line 17, in <module>
    from includes.mitm import *
  File "/root/mytemp/snoopy-ng/includes/mitm.py", line 4, in <module>
    from mitmproxy import proxy, flow, platform
  File "/usr/lib/python2.7/dist-packages/mitmproxy/proxy/__init__.py", line 3, in <module>
    from .config import ProxyConfig
  File "/usr/lib/python2.7/dist-packages/mitmproxy/proxy/config.py", line 15, in <module>
    from netlib import tcp
  File "/usr/lib/python2.7/dist-packages/netlib/tcp.py", line 15, in <module>
    from six.moves import range
ImportError: cannot import name range`

Can anyone offer a solution to this common issue?

**Comment by lugfug** [comment]
I have this same issue. I can't install Snoopy on Kali Linux Rolling , Raspberry Pi 3. The install fails just as described above and the dependencies are not accessible via apt-get or pip installs. 

This software seems like it would be soooo useful. But its just languishing and nothing it getting fixed. Sad when good software dies.
